png(file = "plot1.png")
hist(ECP$Global_active_power,col= "red",main="Global Active Power",xlab="Global Active Power (killowats)")
dev.off()

png(file = "plot2.png")
with(ECP, plot(Time, Global_active_power, ylab = "Global Active Power (killowats)", type="l"))
dev.off()

png(file = "plot3.png")
with(ECP, plot(Time, Sub_metering_1, ylab = "Energy sub metering", type="l"))
with(ECP, lines(Time, Sub_metering_2, col = "red"))
with(ECP, lines(Time, Sub_metering_3, col = "blue"))
legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()

png(file = "plot4.png")
par(mfrow=c(2,2))
with(ECP, plot(Time, Global_active_power, ylab = "Global Active Power (killowats)", type="l"))
with(ECP, plot(Time, Voltage, ylab = "Voltage", type="l"))
with(ECP, plot(Time, Sub_metering_1, ylab = "Energy sub metering", type="l"))
with(ECP, lines(Time, Sub_metering_2, col = "red"))
with(ECP, lines(Time, Sub_metering_3, col = "blue"))
legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(ECP, plot(Time, Global_reactive_power, ylab = "Global Reactive Power", type="l"))
dev.off()